# Exercici 1
#### Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [8]:
import numpy as np
from statistics import mode

def resumDadesArray(matriz):
    if matriz.ndim>1:
        print('Error: La matriu introduïda és de més d´una dimensió.')
    else:
        print('suma: ', matriz.sum()) # suma
        print('minimo: ', matriz.min()) # minimo
        print('maximo: ', matriz.max()) # maximo
        print('mediana: ', np.median(matriz)) # mediana
        print('media: ', matriz.mean()) # media
        print('moda: ', mode(matriz)) # moda
        print('desviacion estandar: ', np.std(matriz)) #desviación estandar
        print('varianza: ', np.var(matriz)) #varianza


In [9]:
mat1= np.array([[1, 5, 3, 4, 5, 6, 7],
                  [1, 5, 3, 4, 5, 6, 7]])

In [10]:
resumDadesArray(mat1)

Error: La matriu introduïda és de més d´una dimensió.


In [14]:
mat2= np.array([1, 5, 3, 4, 5, 6, 7])

In [15]:
resumDadesArray(mat2)

suma:  31
minimo:  1
maximo:  7
mediana:  5.0
media:  4.428571428571429
moda:  5
desviacion estandar:  1.840585532389304
varianza:  3.387755102040817


# Exercici 2
#### Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [92]:
import numpy as np
from numpy import random

def creaArrayQuadrat(k):
    return random.randint(101, size=(k,k))


In [93]:
mat=creaArrayQuadrat(10)
print(mat)

[[46 87 12 94  8 25 49 25 88 21]
 [98 54 81 80 97 17 71 53 59 56]
 [91 90 24 25 19 85  0 38 75 99]
 [27 39 54  5 41 15 93 49 25 78]
 [ 6 66 96 76  6  1 66 26  6  1]
 [33 77 65 50 19 27 37 47 81 54]
 [88 35 58 34 94 25 95 15 24 82]
 [28 26 84 55  1 91 45 81 75 24]
 [89 48  4 68 31 74 78 43 17 13]
 [81 71 90 14 48 22 95 30 58 31]]


# Exercici 3
#### Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [111]:
import numpy as np
from numpy import random

def creaMatriu(columnes, files):
    return random.randint(101, size=(columnes,files)) #Creem una matriu de 

def sumaFilesColumnes(matrix):
    i=1
    j=1
    for x in matrix: #sumatori per files
        print('Suma de la fila ',i, ' és: ',x.sum())
        i+=1

    for x in matrix.T: #sumatori per columnes, transposant la matriu
        print('Suma de la columna ', j, ' és: ', x.sum())
        j+=1

In [112]:
#Primer creem la matriu NxM que haurà de ser l'input de la funció sumaFilesColumnes
matriu=creaMatriu(4,3)
print(matriu)

[[76  2 70]
 [37 83 59]
 [69 83 98]
 [59 21 34]]


In [113]:
sumaFilesColumnes(matriu) # Després cridem la funció perqué calculi el sumatori per files i columnes

Suma de la fila  1  és:  148
Suma de la fila  2  és:  179
Suma de la fila  3  és:  250
Suma de la fila  4  és:  114
Suma de la columna  1  és:  241
Suma de la columna  2  és:  189
Suma de la columna  3  és:  261


# Exercici 4
#### Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [5]:
import numpy as np

def coefCorrelacio(matriu1, matriu2):
    mitja_Matriu1=matriu1.mean()
    mitja_Matriu2=matriu2.mean()
    N=len(matriu1)
    
    print(mitja_Matriu1)
    print(mitja_Matriu2)

    #PEARSON CORRELATION
    #quan traballem amb una mostra de població, la desviació Standard s'ha de dividir entre N-1
    #per això s'ha de posar ddof=1

    desvSt_Matriu1=np.std(matriu1, ddof=1) 
    desvSt_Matriu2=np.std(matriu2, ddof=1)
    print("desvSt_Matriu1: ", (desvSt_Matriu1))
    print("desvSt_Matriu2: ", (desvSt_Matriu2))

    Total=0
    for i in range(N):
        Total=Total+((matriu1[i]-mitja_Matriu1)*(matriu2[i]-mitja_Matriu2))

    correlacionPearson=(Total/(N-1))/(desvSt_Matriu1*desvSt_Matriu2)
    print('Correlacion Pearson con Formula: '+str(correlacionPearson))


In [22]:
altura= np.array([1.67, 1.75, 1.55, 1.87, 1.81, 1.95, 1.70])
peso= np.array([70, 83, 50, 95, 87, 110, 97])

coefCorrelacio(altura, peso)

1.757142857142857
84.57142857142857
desvSt_Matriu1:  0.1332559299136172
desvSt_Matriu2:  19.688043265369153
Correlacion Pearson con Formula: 0.8856597911605012


#### Comprobació:

In [7]:
#Comprobació
from scipy.stats.stats import pearsonr

print(pearsonr(altura,peso))
print(np.corrcoef(altura,peso))

(0.8856597911605013, 0.007976583953138237)
[[1.         0.88565979]
 [0.88565979 1.        ]]
